### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/chilly-wind#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by beardofedu** [comment]
Hello! 👋

**Comment by jjohnonsonjr** [comment]
I am ready for this class.

**Comment by jggould-asc** [comment]
Hello

**Comment by sdas99** [comment]
Howdy!

**Comment by viplavrao** [comment]
hello

**Comment by bwheeler2428** [comment]
hello

**Comment by rwillis970** [comment]
Hi

**Comment by nshekarb4u** [comment]
this is awesome.

**Comment by gyucheonheo** [comment]
Hi

**Comment by cweyhrich** [comment]
hello

**Comment by bcm916** [comment]
Hi

**Comment by dans900** [comment]
Hello, Dan here.

**Comment by sweiss435** [comment]
Hello1

**Comment by am1t5** [comment]
Amit here

**Comment by JonZ632** [comment]
Hello!

**Comment by nholzer497** [comment]
hello!

**Comment by jaw395** [comment]
Hello

**Comment by jaywang66** [comment]
hi

**Comment by sahilsanjay** [comment]
Hi

**Comment by rubenmesta** [comment]
hello

**Comment by DakarBlues** [comment]
Hi, mo here!

**Comment by jjohnonsonjr** [comment]
> Hi
> Jake

Nice to see you Jake.

**Comment by danr512** [comment]
Hi

**Comment by phillip-cloud** [comment]
Hello there

**Comment by hjzhu073** [comment]
Hello world!

**Comment by jvattathara** [comment]
I am in

**Comment by rdalmos** [comment]
Hi

**Comment by lyle-ascn** [comment]
Hello from Kansas

**Comment by neelamp-class** [comment]
Hi

**Comment by AravindGana** [comment]
Hello

**Comment by Mukeshkumar84** [comment]
hi

**Comment by sushmitha10** [comment]
Hello

**Comment by pavlonator** [comment]
Pavlo here

**Comment by tnash99** [comment]
ok

**Comment by djtvky** [comment]
welcome

**Comment by kishoresun** [comment]
i am in

**Comment by rodrigofuentes** [comment]
add plox

**Comment by huangrh** [comment]
add me

**Comment by huangrh** [comment]
add me

**Comment by Subhashiram** [comment]
Hello this is Subhashini
